In [2]:
import numpy as np
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A) # lúc này temp = A^2
print("Ma trận A^2:\n", temp)

temp = temp.dot(A) # lúc này temp = A^3
print("Ma trận A^3:\n", temp)

A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
    temp = temp.dot(A)
    sumA = sumA + temp  
print("temp:\n", temp)
print("Ma trận S = A + A^2 + A^3:\n", sumA)

Ma trận A^2:
 [[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]
Ma trận A^3:
 [[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
temp:
 [[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
Ma trận S = A + A^2 + A^3:
 [[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]
