In [ ]:
from scipy import linalg # Tải gói linalg của scipy vào bộ nhớ (để sử dụng)
import numpy as np # Tải gói numpy vào sử dụng với tên gọi là np
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]]) # ma trận số thực 
# Các kiểu khai báo và khởi tạo ma trận: 
A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b) # Chuyển b thành dạng ma trận
C = np.matrix(np.random.random( (10,5) ) )
D = np.matrix([ [4, 3], [2, 6] ])
F = np.eye(3, k=1) # tạo ma trận đường chéo. 3 là ma trận 3x3, k=1 là đường
# chéo nằm phía trên đường chéo chính (k = 0)
print("Ma trận A:\n", A)
print("Ma trận B:\n", B)
print("Ma trận C:\n", C)
print("Ma trận D:\n", D)
print("Ma trận F:\n", F)

Ma trận A:
 [[0.43141515 0.10383282]
 [0.96716525 0.79369362]]
Ma trận B:
 [[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
Ma trận C:
 [[0.20455703 0.28924734 0.9448908  0.85996777 0.24373272]
 [0.30625695 0.72425141 0.58029338 0.02112096 0.53606008]
 [0.39746883 0.8419533  0.54149223 0.95758362 0.93517946]
 [0.33136989 0.6357499  0.63022968 0.98634738 0.98127723]
 [0.43932291 0.12411127 0.06011569 0.22844234 0.6009662 ]
 [0.32761392 0.52445224 0.87551793 0.48033301 0.44403405]
 [0.43362093 0.42147477 0.40377978 0.05388437 0.5802251 ]
 [0.9853895  0.02313016 0.42032195 0.15919271 0.65336631]
 [0.89361479 0.66232523 0.38532428 0.08830734 0.61422009]
 [0.7557203  0.03021515 0.4044672  0.89434631 0.14679343]]
Ma trận D:
 [[4 3]
 [2 6]]
Ma trận F:
 [[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [2]:
# Các phép xử lý đơn giản 
# Xem hạng ma trận: 
print("Hạng của ma trận C:", np.linalg.matrix_rank(C))
# Tính ma trận nghịch đảo: 
print("Ma trận nghịch đảo của A:\n", A.I)
print("Ma trận nghịch đảo của A (sử dụng scipy.linalg.inv):\n", linalg.inv(A))
# Định thức ma trận: 
print("Định thức của A:", linalg.det(A))
# Chuyển đổi ma trận: 
print("Chuyển vị của A:\n", A.T)
print("Chuyển vị liên hợp của A:\n", A.H)

Hạng của ma trận C: 5
Ma trận nghịch đảo của A:
 [[ 3.27988891 -0.42908259]
 [-3.9967495   1.78279594]]
Ma trận nghịch đảo của A (sử dụng scipy.linalg.inv):
 [[ 3.27988891 -0.42908259]
 [-3.9967495   1.78279594]]
Định thức của A: 0.24198795896569883
Chuyển vị của A:
 [[0.43141515 0.96716525]
 [0.10383282 0.79369362]]
Chuyển vị liên hợp của A:
 [[0.43141515 0.96716525]
 [0.10383282 0.79369362]]


In [3]:
# Giải các loại phương trình tuyến tính: 
print("Nghiệm của phương trình Ax = b là:\n", linalg.solve(A, b))

E = np.matrix(a).T 
print(linalg.lstsq(F, E)) # Giải phương trình xấp xỉ F*x = E

Nghiệm của phương trình Ax = b là:
 [[ 3.27988891+27.80266983j  0.         +4.41436488j
   0.         +7.2651712j ]
 [-3.9967495 -28.83956172j -0.         +0.92048071j
   0.         -1.29347284j]]
(array([[0.],
       [1.],
       [2.]]), array([], dtype=float64), 2, array([1., 1., 0.]))


In [4]:
# Các hàm trên ma trận 
print("Tổng của A và D:\n", np.add(A, D))

print("Hiệu của A và D:\n", np.subtract(A, D))

print("Thương của A và D:\n", np.divide(A, D))

print("Tích của A và D:\n", A @ D)

print("Tích của D và A:\n", np.multiply(D, A))

print("Tích của A và D:\n", np.dot(A, D))

print("Tích của A và D:\n", np.vdot(A, D))

Tổng của A và D:
 [[4.43141515 3.10383282]
 [2.96716525 6.79369362]]
Hiệu của A và D:
 [[-3.56858485 -2.89616718]
 [-1.03283475 -5.20630638]]
Thương của A và D:
 [[0.10785379 0.03461094]
 [0.48358263 0.13228227]]
Tích của A và D:
 [[1.93332624 1.91724237]
 [5.45604826 7.6636575 ]]
Tích của D và A:
 [[1.7256606  0.31149846]
 [1.93433051 4.76216174]]
Tích của A và D:
 [[1.93332624 1.91724237]
 [5.45604826 7.6636575 ]]
Tích của A và D:
 [[1.7256606]]


In [5]:
# Hàm lũy thừa và logarith ma trận:
print("Ma trận lũy thừa của A:\n", linalg.expm(A))

print("Ma trận logarith của A:\n", linalg.logm(A))

Ma trận lũy thừa của A:
 [[1.62772948 0.1958687 ]
 [1.82444623 2.31112623]]
Ma trận logarith của A:
 [[-1.0502338   0.19535381]
 [ 1.81965026 -0.36863351]]
