In [109]:
import numpy as np

n = 4
X = np.array(range(1, n+1))   # X = [1, 2, 3, 4]

def sgn_by_def(sigma):
    ketqua = 1
    n = len(sigma)
    for i in range(n-1):
        for j in range(i+1, n):
            ketqua *= (sigma[i] - sigma[j]) / (i - j)
    return int(ketqua)

sigma = np.array([2, 1, 3, 4])
sgn_by_def(sigma)

-1

In [110]:
sigma = np.array([1,2,3,4])
sgn_by_def(sigma) 

1

In [111]:
sigma = np.array([4,3,2,1])
sgn_by_def(sigma)

1

In [112]:
from itertools import permutations
n = 3
X = []
for i in range (1, n+1):
 X.append(i)
Sn = list(permutations(X)) # tạo hoán vị của tập X
print (Sn)

[(1, 2, 3), (1, 3, 2), (2, 1, 3), (2, 3, 1), (3, 1, 2), (3, 2, 1)]


In [113]:
Sn[3].index(2) # sẽ là 0 vì 2 ở là vị trí đầu tiên của Sn[3]. 
det = 0 # bước này có duy nhất 1 lệnh, có ý nghĩa khởi tạo giá trị ban đầu của định thức.
import numpy as np 

def phatsinh_dinhthuc(n):
    X = []
    for i in range(1, n+1):
        X.append(i)

    Sn = list(permutations(X))
    dinhthuc = ""

    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = ""

        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product + "a" + str(i) + str(sn.index(i) + 1)

        dau = sgn_by_def(sigma)

        if (dau != 1):
            product = " - " + product
        else:
            product = " + " + product

        dinhthuc = dinhthuc + product

    return dinhthuc

# sgn_by_def(sigma) là gọi hàm bên phía trên đã xây dựng
phatsinh_dinhthuc(3)

' + a11a22a33 - a11a23a32 - a12a21a33 + a13a21a32 + a12a23a31 - a13a22a31'

In [114]:
def tinhtoan_dinhthuc(A):
    X = []
    import math                    # <-- bổ sung để sử dụng sqrt
    n = int(math.sqrt(A.size))     # <-- với ma trận vuông, kích thước là căn số
    for i in range(1, n+1):
        X.append(i)

    Sn = list(permutations(X))
    dinhthuc = 0                   # ban đầu giá trị định thức là 0

    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1               # đặt giá trị cho tích ban đầu là 1

        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product = product * A[i-1][sn.index(i)]   # lưu ý chỉ số
            # print(A[i-1][sn.index(i)])

        dau = sgn_by_def(sigma)

        if (dau != 1):             # không xét trường hợp dấu = 1
            product = product * (-1)   # khi dấu = -1 thì nhân với -1

        dinhthuc = dinhthuc + product

    return dinhthuc

matran = np.array([ [3,5,-8], [4, 12, -1], [2,5,3] ])
tinhtoan_dinhthuc(matran) # MT A

np.int64(85)

In [115]:
import numpy as np
A = np.array([[4, -2],[3, -5]]) # khai báo ma trận A
A1 = np.array([[10, -2],[11, -5]])
A2 = np.array([[4, 10],[3, 11]])
from scipy import linalg # lưu ý: hàm tính định thức của ma trận là scipy.linalg.det(A)
detA = linalg.det(A) # tính định thức cho ma trận A
detA1 = linalg.det(A1)
detA2 = linalg.det(A2)
print (detA, detA1, detA2) 

-14.0 -28.0 14.000000000000004


In [116]:
if (detA != 0):
    x1 = detA1 / detA
    x2 = detA2 / detA
    print ("Hai nghiệm của phương trình là: ", x1, x2) 

Hai nghiệm của phương trình là:  2.0 -1.0000000000000002


In [117]:
import numpy as np
from itertools import permutations


print(tinhtoan_dinhthuc(A))
print(tinhtoan_dinhthuc(A1))
print(tinhtoan_dinhthuc(A2))

-14
-28
14


In [ ]:
# Sử dụng hàm det() của lớp linalg của thư viện scipy
import numpy as np
A = np.array([
    [-1,  2, -3],
    [ 2, -2,  1],
    [ 3, -4,  4]
])
B = np.array([1, 3, 2])
A1 = np.array([
    [ 1,  2, -3],
    [ 3, -2,  1],
    [ 2, -4,  4]
])
A2 = np.array([
    [-1,  1, -3],
    [ 2,  3,  1],
    [ 3,  2,  4]
])
A3 = np.array([
    [-1,  2,  1],
    [ 2, -2,  3],
    [ 3, -4,  2]
])
from scipy import linalg
detA  = linalg.det(A)
detA1 = linalg.det(A1)
detA2 = linalg.det(A2)
detA3 = linalg.det(A3)
print(detA, detA1, detA2, detA3)
x = detA1 / detA
y = detA2 / detA
z = detA3 / detA
print(x, y, z)

0.0 0.0 0.0 0.0
nan nan nan


C:\Users\Tran Thinh\AppData\Local\Temp\ipykernel_25304\2951892445.py:35: RuntimeWarning: invalid value encountered in scalar divide
  x = detA1 / detA
C:\Users\Tran Thinh\AppData\Local\Temp\ipykernel_25304\2951892445.py:36: RuntimeWarning: invalid value encountered in scalar divide
  y = detA2 / detA
C:\Users\Tran Thinh\AppData\Local\Temp\ipykernel_25304\2951892445.py:37: RuntimeWarning: invalid value encountered in scalar divide
  z = detA3 / detA


In [ ]:
# Sử dụng hàm tinhtoan_dinhthuc() viết bên trên 

detA  = tinhtoan_dinhthuc(A)
detA1 = tinhtoan_dinhthuc(A1)
detA2 = tinhtoan_dinhthuc(A2)
detA3 = tinhtoan_dinhthuc(A3)

print(detA, detA1, detA2, detA3)


0 0 0 0


In [ ]:
import numpy as np
from scipy import linalg
# Ma trận hệ số
A = np.array([
    [-1,  2, -3],
    [ 2, -2,  1],
    [ 3, -4,  4]
])
# Vector hằng số
B = np.array([1, 3, 2])
# Các ma trận theo quy tắc Cramer
Ax = np.array([
    [1,  2, -3],
    [3, -2,  1],
    [2, -4,  4]
])
Ay = np.array([
    [-1, 1, -3],
    [ 2, 3,  1],
    [ 3, 2,  4]
])
Az = np.array([
    [-1,  2, 1],
    [ 2, -2, 3],
    [ 3, -4, 2]
])
# Tính định thức
detA  = linalg.det(A)
detAx = linalg.det(Ax)
detAy = linalg.det(Ay)
detAz = linalg.det(Az)
# Kiểm tra điều kiện có nghiệm duy nhất
if abs(detA) < 1e-10:
    print("Hệ phương trình không có nghiệm duy nhất (detA = 0)")
else:
    x = detAx / detA
    y = detAy / detA
    z = detAz / detA
    print("Nghiệm của hệ phương trình:")
    print("x =", x)
    print("y =", y)
    print("z =", z)
x, y, z = detAx/detA, detAy/detA, detAz/detA  # tính toán x, y, z
print ("Nghiệm của phương trình: ", "x=", x, "y=", y, "z = ", z) 

Hệ phương trình không có nghiệm duy nhất (detA = 0)
Nghiệm của phương trình:  x= nan y= nan z =  nan


C:\Users\Tran Thinh\AppData\Local\Temp\ipykernel_25304\3536226587.py:51: RuntimeWarning: invalid value encountered in scalar divide
  x, y, z = detAx/detA, detAy/detA, detAz/detA  # tính toán x, y, z


In [129]:
import numpy as np
# Ma trận hệ số
A = np.array([
    [-1,  2, -3],
    [ 2, -2,  1],
    [ 3, -4,  4]
])
# Vector hằng số
B = np.array([1, 3, 2])
# Ma trận Cramer
AX = np.array([
    [1,  2, -3],
    [3, -2,  1],
    [2, -4,  4]
])
AY = np.array([
    [-1, 1, -3],
    [ 2, 3,  1],
    [ 3, 2,  4]
])
AZ = np.array([
    [-1,  2, 1],
    [ 2, -2, 3],
    [ 3, -4, 2]
])
# Tính định thức bằng hàm đã viết
det  = tinhtoan_dinhthuc(A)
detX = tinhtoan_dinhthuc(AX)
detY = tinhtoan_dinhthuc(AY)
detZ = tinhtoan_dinhthuc(AZ)
# Tính nghiệm
x, y, z = detX/det, detY/det, detZ/det
print("Nghiệm", "x =", x, "y =", y, "z =", z)

Nghiệm x = nan y = nan z = nan


C:\Users\Tran Thinh\AppData\Local\Temp\ipykernel_25304\248902110.py:32: RuntimeWarning: invalid value encountered in scalar divide
  x, y, z = detX/det, detY/det, detZ/det


In [131]:
import sympy as sp
TG = sp.Matrix([[1, 0, 1],[4, 3, 1], [2, 2, 1]])
1/2*TG.det()
print(1/2*TG.det())

1.50000000000000


In [132]:
from sympy import Matrix

M = Matrix([[0, 4, 1, 1], [4, 0, 0, 1], [3, 5, 2, 1], [2, 2, 5, 1]])
print(M.det())
print(1/6*M.det())

-72
-12.0000000000000


In [133]:
from sympy import * # lúc này ta sử dụng trực tiếp thư viện
x, y, z = symbols('x y z')
MP = Matrix([[x, y, z, 1],[-1, 3, 2, 1],[0, 1, 0, 1],[-2, 0, 1, 1]])
print(MP.det())

-4*x + 3*y - 5*z - 3


In [ ]:
# Câu 1:
import numpy as np
from scipy import linalg
# Tính ma trận hệ số kép
def cofactor_matrix(A):
    n = A.shape[0]
    C = np.zeros((n, n))
    
    for i in range(n):
        for j in range(n):
            # Ma trận con M_ij
            M = np.delete(np.delete(A, i, axis=0), j, axis=1)
            C[i, j] = ((-1)**(i + j)) * linalg.det(M)
    return C

# Tính ma trận liên hợp
def adjoint_matrix(A):
    return cofactor_matrix(A).T
# Ví dụ minh họa
A = np.array([
    [1, 2, 3],
    [0, 4, 5],
    [1, 0, 6]
])
C = cofactor_matrix(A)
Adj = adjoint_matrix(A)
print("Ma trận A:")
print(A)
print("\nMa trận hệ số kép:")
print(C)
print("\nMa trận liên hợp:")
print(Adj)

Ma trận A:
[[1 2 3]
 [0 4 5]
 [1 0 6]]

Ma trận hệ số kép:
[[ 24.   5.  -4.]
 [-12.   3.   2.]
 [ -2.  -5.   4.]]

Ma trận liên hợp:
[[ 24. -12.  -2.]
 [  5.   3.  -5.]
 [ -4.   2.   4.]]


In [136]:
# Câu 2:    
import sympy as sp
# Khai báo biến
x, y = sp.symbols('x y')
# Ba điểm đã biết
x1, y1 = 1, 2
x2, y2 = 4, 6
x3, y3 = 5, 2
# Lập ma trận định thức
M = sp.Matrix([
    [x**2 + y**2, x, y, 1],
    [x1**2 + y1**2, x1, y1, 1],
    [x2**2 + y2**2, x2, y2, 1],
    [x3**2 + y3**2, x3, y3, 1]
])
# Tính định thức
circle_eq = sp.expand(M.det())
print("Phương trình đường tròn:")
print(circle_eq, "= 0")

Phương trình đường tròn:
-16*x**2 + 96*x - 16*y**2 + 116*y - 248 = 0
